### ISSUE TITLE
Email Preview Display?

### ISSUE THREAD

**Issue by alisiamartz** [alisiamartz/CMPM_MERGED#2]
I don't know if this was purposeful or not, but the email previews displayed on the screen are just "date, sender, subject, content" emails that contain no people. I may be wrong, but I thought that this was all added in for this due date?

Luckily we have until tomorrow at 8 to resubmit and I extremely urge everyone to check out the code and make sure it's working properly.

**Comment by GreenCyan** [comment]
The emails seem to work fine for me...

**Comment by GreenCyan** [comment]
the console does keep saying "par" is undefined though...

**Comment by alisiamartz** [comment]
son fixed it!
